In [8]:
import numpy as np

In [9]:
my_list = [1,2,3]

In [7]:
arr = np.array(my_list)

In [10]:
arr

array([1, 2, 3])

In [12]:
my_mat = [[1,2,3], [4,5,6],[7,8,9]]

In [14]:
my_mat

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [18]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
np.arange(0, 11, 2)

array([ 0,  2,  4,  6,  8, 10])

In [26]:
np.zeros(3)

array([0., 0., 0.])

In [30]:
np.zeros((2, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [31]:
np.ones(4)

array([1., 1., 1., 1.])

In [33]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [35]:
np.linspace(0, 5, 100)

array([0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
       0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545,
       0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
       0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596,
       1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
       1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646,
       1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
       1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697,
       2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
       2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747,
       2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
       2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798,
       3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
       3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848,
       3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737

In [37]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [39]:
np.random.rand(5)

array([0.44878522, 0.52461052, 0.20687322, 0.74874399, 0.38097082])

In [41]:
np.random.rand(5,5)

array([[0.99519243, 0.69943   , 0.652957  , 0.58939505, 0.34543114],
       [0.19751985, 0.802223  , 0.03987443, 0.87314821, 0.11231642],
       [0.65215891, 0.59201069, 0.94118674, 0.06693589, 0.73292079],
       [0.52138713, 0.34666031, 0.85449883, 0.85246045, 0.94087639],
       [0.4782559 , 0.32563002, 0.4094333 , 0.33130694, 0.91186125]])

In [43]:
np.random.randn(2)

array([0.96929653, 0.20836845])

In [45]:
np.random.randn(2, 2)

array([[ 0.06280904, -1.07490897],
       [-0.05037236,  0.33051126]])

In [47]:
np.random.randint(1, 100)

20

In [52]:
np.random.randint(1, 100, 10)

array([ 3,  6,  2, 18, 90, 21, 76, 79, 91, 57])

In [53]:
arr = np.arange(25)

In [54]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [55]:
ranarr = np.random.randint(0, 50, 10)

In [56]:
ranarr

array([18, 29, 10, 40, 21, 27,  4, 29, 45, 26])

In [ ]:
arr.reshape(5, 5)