In [8]:
import numpy as np

In [9]:
my_list = [1,2,3]

In [7]:
arr = np.array(my_list)

In [10]:
arr

array([1, 2, 3])

In [12]:
my_mat = [[1,2,3], [4,5,6],[7,8,9]]

In [14]:
my_mat

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [18]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
np.arange(0, 11, 2)

array([ 0,  2,  4,  6,  8, 10])